use_frameworks!

platform :ios, '8.0'

target 'KLCollectionViewFlowLayout_Example' do
  pod 'KLCollectionViewFlowLayout', :path => '../'

  target 'KLCollectionViewFlowLayout_Tests' do
    inherit! :search_paths

    
  end
end
